// PRODUCT APIS ACTIONS
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS"

// UI ACTIONS
export const SHOW_PRODUCT_SEARCH_COMPONENT = "SHOW_PRODUCT_SEARCH_COMPONENT"